GALLERY = {
    "white_sedan": "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "white_bmw": "https://images.pexels.com/photos/14776716/pexels-photo-14776716.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "white_forest": "https://images.pexels.com/photos/11039663/pexels-photo-11039663.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "white_parked": "https://images.unsplash.com/photo-1689264023564-607c57ede91a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "white_lot": "https://images.unsplash.com/photo-1712524651532-82380bca59bb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "black_merc": "https://images.unsplash.com/photo-1764090317825-9b76e437c8d8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "black_merc2": "https://images.unsplash.com/photo-1779025313068-b4a11d86bf0d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "black_saloon": "https://images.unsplash.com/photo-1764089859665-7d417664c5de?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "tesla": "https://images.unsplash.com/photo-1615829386703-e2bb66a7cb7d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "tesla2": "https://images.unsplash.com/photo-1615901555268-839b7a1ede54?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
}

def _photos(*keys):
    return [GALLERY[k] for k in keys]

LISTINGS = [
    {"id": "ve-001", "make": "Toyota", "model": "Prius", "year": 2022, "colour": "Silver",
     "plate": "LK22 CAR", "vehicle_type": "saloon", "fuel": "hybrid", "mpg": 65, "seats": 5,
     "weekly_rent": 265, "deposit": 400, "mileage_allowance": 1200, "min_experience": 1,
     "borough": "Newham", "postcode": "E13", "breakdown_included": True,
     "designated_garage": "Stratford Motors", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "NE-2291", "operator_rating": 4.8, "operator_rentals": 63,
     "operator_since": 2021, "operator_response": "under 2 hours", "mileage": 47300,
     "features": ["Dash cam", "ULEZ compliant", "Apple CarPlay", "Rear camera"],
     "description": "Well-maintained hybrid, ULEZ compliant, dash cam fitted front and rear. Full service history, serviced every 10,000 miles at our designated garage in Stratford. Available for immediate handover.",
     "photos": _photos("white_sedan", "white_parked", "white_lot", "black_merc2")},

    {"id": "ve-002", "make": "Ford", "model": "Galaxy", "year": 2021, "colour": "Grey",
     "plate": "LG21 GXY", "vehicle_type": "mpv", "fuel": "diesel", "mpg": 48, "seats": 7,
     "weekly_rent": 245, "deposit": 450, "mileage_allowance": 1200, "min_experience": 2,
     "borough": "Croydon", "postcode": "CR0", "breakdown_included": True,
     "designated_garage": "Croydon Fleet Services", "wear_tear": "Standard", "restrictions": "No airport runs after midnight",
     "operator_code": "CR-1187", "operator_rating": 4.6, "operator_rentals": 41,
     "operator_since": 2020, "operator_response": "under 4 hours", "mileage": 62100,
     "features": ["7 seats", "ULEZ compliant", "Parking sensors"],
     "description": "Spacious 7-seat MPV, ideal for group and airport work. Regularly serviced, ULEZ compliant, breakdown cover included.",
     "photos": _photos("white_forest", "white_bmw", "white_parked", "black_saloon")},

    {"id": "ve-003", "make": "Tesla", "model": "Model 3", "year": 2023, "colour": "White",
     "plate": "TM23 EVX", "vehicle_type": "executive", "fuel": "electric", "mpg": 0, "seats": 5,
     "weekly_rent": 340, "deposit": 600, "mileage_allowance": 1500, "min_experience": 2,
     "borough": "Redbridge", "postcode": "IG1", "breakdown_included": False,
     "designated_garage": "Ilford EV Centre", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "IG-3350", "operator_rating": 4.9, "operator_rentals": 88,
     "operator_since": 2019, "operator_response": "under 1 hour", "mileage": 21400,
     "features": ["330 mile range", "Autopilot", "Premium interior", "Fast charging"],
     "description": "Long-range Model 3, premium executive vehicle with autopilot. Low running costs, perfect for high-mileage executive work. Charging network access included.",
     "photos": _photos("tesla", "tesla2", "white_lot", "black_merc")},

    {"id": "ve-004", "make": "Skoda", "model": "Octavia", "year": 2020, "colour": "Blue",
     "plate": "SK20 OCT", "vehicle_type": "estate", "fuel": "diesel", "mpg": 58, "seats": 5,
     "weekly_rent": 210, "deposit": 350, "mileage_allowance": 1000, "min_experience": 0,
     "borough": "Harrow", "postcode": "HA1", "breakdown_included": True,
     "designated_garage": "Harrow Auto Care", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "HA-0824", "operator_rating": 4.5, "operator_rentals": 29,
     "operator_since": 2021, "operator_response": "same day", "mileage": 71200,
     "features": ["Large boot", "ULEZ compliant", "Economical"],
     "description": "Reliable and economical estate with a huge boot. Great value weekly rent, ideal for new drivers. Breakdown cover included.",
     "photos": _photos("white_parked", "white_sedan", "white_bmw", "black_saloon")},

    {"id": "ve-005", "make": "Toyota", "model": "Camry", "year": 2022, "colour": "Black",
     "plate": "LK22 CMY", "vehicle_type": "saloon", "fuel": "hybrid", "mpg": 57, "seats": 5,
     "weekly_rent": 280, "deposit": 450, "mileage_allowance": 1300, "min_experience": 1,
     "borough": "Newham", "postcode": "E13", "breakdown_included": True,
     "designated_garage": "Stratford Motors", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "NE-2291", "operator_rating": 4.8, "operator_rentals": 63,
     "operator_since": 2021, "operator_response": "under 2 hours", "mileage": 38900,
     "features": ["Leather seats", "ULEZ compliant", "Dash cam", "Comfort ride"],
     "description": "Comfortable hybrid saloon, popular with executive passengers. Leather interior, low emissions, full service history.",
     "photos": _photos("black_merc", "black_merc2", "white_sedan", "white_lot")},

    {"id": "ve-006", "make": "Volkswagen", "model": "Caddy WAV", "year": 2021, "colour": "White",
     "plate": "BK21 WAV", "vehicle_type": "wav", "fuel": "diesel", "mpg": 45, "seats": 5,
     "weekly_rent": 255, "deposit": 500, "mileage_allowance": 1100, "min_experience": 2,
     "borough": "Barking & Dagenham", "postcode": "IG11", "breakdown_included": True,
     "designated_garage": "Barking Commercial", "wear_tear": "Standard", "restrictions": "Accessibility trained drivers preferred",
     "operator_code": "BK-4410", "operator_rating": 4.7, "operator_rentals": 19,
     "operator_since": 2022, "operator_response": "under 3 hours", "mileage": 54300,
     "features": ["Wheelchair accessible", "Ramp fitted", "ULEZ compliant"],
     "description": "Wheelchair-accessible vehicle with rear ramp. In demand for accessible PHV work across East London. Breakdown cover included.",
     "photos": _photos("white_lot", "white_parked", "white_forest", "black_merc2")},

    {"id": "ve-007", "make": "Mercedes-Benz", "model": "E-Class", "year": 2021, "colour": "Black",
     "plate": "ME21 EXC", "vehicle_type": "executive", "fuel": "diesel", "mpg": 52, "seats": 5,
     "weekly_rent": 355, "deposit": 700, "mileage_allowance": 1400, "min_experience": 3,
     "borough": "Westminster", "postcode": "SW1", "breakdown_included": True,
     "designated_garage": "Victoria Prestige", "wear_tear": "Enhanced", "restrictions": "3+ years experience",
     "operator_code": "WM-5567", "operator_rating": 4.9, "operator_rentals": 102,
     "operator_since": 2018, "operator_response": "under 1 hour", "mileage": 44800,
     "features": ["Executive interior", "Leather", "Sat nav", "Premium sound"],
     "description": "Premium executive saloon for high-end private hire and chauffeur work. Immaculate condition, enhanced wear-and-tear cover, breakdown included.",
     "photos": _photos("black_merc", "black_saloon", "black_merc2", "white_bmw")},

    {"id": "ve-008", "make": "BMW", "model": "3 Series", "year": 2020, "colour": "White",
     "plate": "BM20 SER", "vehicle_type": "executive", "fuel": "petrol", "mpg": 44, "seats": 5,
     "weekly_rent": 300, "deposit": 600, "mileage_allowance": 1200, "min_experience": 2,
     "borough": "Camden", "postcode": "NW1", "breakdown_included": False,
     "designated_garage": "Camden Motorworks", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "CM-2204", "operator_rating": 4.6, "operator_rentals": 47,
     "operator_since": 2020, "operator_response": "under 5 hours", "mileage": 58600,
     "features": ["Sport interior", "Alloy wheels", "Sat nav"],
     "description": "Sporty executive saloon with strong ratings. Popular for executive app work. Breakdown cover available as an add-on.",
     "photos": _photos("white_bmw", "white_forest", "white_sedan", "black_merc")},

    {"id": "ve-009", "make": "Toyota", "model": "Corolla", "year": 2022, "colour": "Grey",
     "plate": "TC22 COR", "vehicle_type": "saloon", "fuel": "hybrid", "mpg": 62, "seats": 5,
     "weekly_rent": 250, "deposit": 400, "mileage_allowance": 1250, "min_experience": 0,
     "borough": "Hounslow", "postcode": "TW3", "breakdown_included": True,
     "designated_garage": "Hounslow Hybrid Hub", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "HO-3391", "operator_rating": 4.7, "operator_rentals": 55,
     "operator_since": 2021, "operator_response": "under 3 hours", "mileage": 33100,
     "features": ["ULEZ compliant", "Dash cam", "Low running costs", "Apple CarPlay"],
     "description": "Efficient hybrid saloon near Heathrow, ideal for airport work. Low fuel costs, breakdown cover included, well maintained.",
     "photos": _photos("white_parked", "white_sedan", "white_lot", "black_merc2")},

    {"id": "ve-010", "make": "Nissan", "model": "Leaf", "year": 2021, "colour": "Blue",
     "plate": "NL21 EVL", "vehicle_type": "saloon", "fuel": "electric", "mpg": 0, "seats": 5,
     "weekly_rent": 235, "deposit": 450, "mileage_allowance": 1000, "min_experience": 1,
     "borough": "Lewisham", "postcode": "SE13", "breakdown_included": True,
     "designated_garage": "Lewisham EV Works", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "LW-7712", "operator_rating": 4.4, "operator_rentals": 24,
     "operator_since": 2022, "operator_response": "same day", "mileage": 29800,
     "features": ["168 mile range", "ULEZ exempt", "Fast charge", "Low running costs"],
     "description": "Fully electric, zero emissions and ULEZ exempt. Very low running costs for city work. Breakdown cover and home-charge guidance included.",
     "photos": _photos("tesla2", "tesla", "white_parked", "white_bmw")},

    {"id": "ve-011", "make": "Vauxhall", "model": "Insignia", "year": 2019, "colour": "Silver",
     "plate": "VI19 INS", "vehicle_type": "saloon", "fuel": "diesel", "mpg": 50, "seats": 5,
     "weekly_rent": 195, "deposit": 300, "mileage_allowance": 1000, "min_experience": 0,
     "borough": "Ealing", "postcode": "W5", "breakdown_included": False,
     "designated_garage": "Ealing Motor Group", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "EA-8830", "operator_rating": 4.3, "operator_rentals": 31,
     "operator_since": 2021, "operator_response": "same day", "mileage": 78200,
     "features": ["Budget friendly", "Spacious", "Cruise control"],
     "description": "Budget-friendly saloon, our lowest weekly rate. Great for drivers starting out. Breakdown cover available as an add-on.",
     "photos": _photos("white_forest", "white_parked", "white_sedan", "black_saloon")},

    {"id": "ve-012", "make": "Kia", "model": "Niro", "year": 2022, "colour": "Grey",
     "plate": "KN22 NRO", "vehicle_type": "estate", "fuel": "hybrid", "mpg": 60, "seats": 5,
     "weekly_rent": 260, "deposit": 450, "mileage_allowance": 1200, "min_experience": 1,
     "borough": "Bromley", "postcode": "BR1", "breakdown_included": True,
     "designated_garage": "Bromley Service Centre", "wear_tear": "Standard", "restrictions": "None",
     "operator_code": "BR-4419", "operator_rating": 4.6, "operator_rentals": 38,
     "operator_since": 2021, "operator_response": "under 4 hours", "mileage": 41500,
     "features": ["ULEZ compliant", "Roomy boot", "Reversing camera", "Economical"],
     "description": "Practical hybrid crossover with plenty of space and low fuel costs. Breakdown cover included, full service history.",
     "photos": _photos("white_bmw", "white_lot", "white_forest", "black_merc")},
]
